language: objective-c
osx_image: xcode8.2
sudo: false
cache:
  - bundler
  - cocoapods
podfile: TaskTimer/Podfile

before_install:

env:
  - DESTINATION='platform=iOS Simulator,name=iPhone 6s Plus,OS=10.2' UITEST=1
  - DESTINATION='platform=iOS Simulator,name=iPad Air,OS=9.3' UITEST=1

script:
  - cd TaskTimer
  - bundle exec fastlane ios test
  - bundle exec fastlane ios lint
  - cd -
