platform :ios, '9.0'
use_frameworks!

target 'TaskTimerModel' do

  pod 'CoreStore'

  target 'TaskTimerModelTests' do
    inherit! :search_paths
  end

end

target 'TaskTimer' do

  pod 'Alamofire', '~> 4.2'
  pod 'Eureka', :git => 'https://github.com/xmartlabs/Eureka.git', :branch => 'master'

  pod 'Fabric'
  pod 'Crashlytics'

  target 'TaskTimerTests' do
    inherit! :search_paths
  end

end
