# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
use_frameworks!

target 'TaskTimer' do

  pod 'Alamofire', '~> 4.2'
  pod 'CoreStore', :git => 'https://github.com/JohnEstropia/CoreStore.git', :branch => 'swift3_develop'
  pod 'Eureka', :git => 'https://github.com/xmartlabs/Eureka.git', :branch => 'master'

  target 'TaskTimerTests' do
    inherit! :search_paths
  end

end
